### ISSUE TITLE
How can I add other vehicles to this code and let them drive automatically at random?

### ISSUE THREAD

**Issue by KangChou** [MankaranSingh/Auto-Depth#8]
hello !
How can I add other vehicles to this code and let them drive automatically at random?

**Comment by MankaranSingh** [comment]
Hi, before running the script provided in this repo, you can run spawn_npc.py script that comes included with CARLA in PythonAPI\examples.  

Hope this helps.

**Comment by KangChou** [comment]
runing train.py:

What should I do to solve the following error? This needs your help.

`Epoch 1/20
2020-12-16 15:03:45.095319: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-12-16 15:03:46.193972: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-12-16 15:03:47.085713: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "D:/Simulation_box/WindowsNoEditor/PythonAPI/Auto-Depth/train.py", line 42, in <module>
    main()
  File "D:/Simulation_box/WindowsNoEditor/PythonAPI/Auto-Depth/train.py", line 39, in main
    validation_data= val_generator)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\keras\engine\training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\keras\engine\training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\keras\engine\training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\keras\backend.py", line 3792, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\eager\function.py", line 1605, in __call__
    return self._call_impl(args, kwargs)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\eager\function.py", line 1645, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\eager\function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\eager\function.py", line 598, in call
    ctx=ctx)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node conv2d_1/convolution (defined at \Users\Anaconda3\envs\tf2-gpu\lib\site-packages\keras\backend\tensorflow_backend.py:3009) ]] [Op:__inference_keras_scratch_graph_12068]

Function call stack:
keras_scratch_graph


Process finished with exit code 1
`

**Comment by KangChou** [comment]
runing train.py:

What should I do to solve the following error? This needs your help.
```
Epoch 1/20
2020-12-16 15:03:45.095319: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-12-16 15:03:46.193972: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-12-16 15:03:47.085713: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "D:/Simulation_box/WindowsNoEditor/PythonAPI/Auto-Depth/train.py", line 42, in <module>
    main()
  File "D:/Simulation_box/WindowsNoEditor/PythonAPI/Auto-Depth/train.py", line 39, in main
    validation_data= val_generator)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\keras\engine\training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\keras\engine\training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\keras\engine\training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\keras\backend.py", line 3792, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\eager\function.py", line 1605, in __call__
    return self._call_impl(args, kwargs)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\eager\function.py", line 1645, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\eager\function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\eager\function.py", line 598, in call
    ctx=ctx)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node conv2d_1/convolution (defined at \Users\Anaconda3\envs\tf2-gpu\lib\site-packages\keras\backend\tensorflow_backend.py:3009) ]] [Op:__inference_keras_scratch_graph_12068]

Function call stack:
keras_scratch_graph


Process finished with exit code 1
```

**Comment by KangChou** [comment]
runing data_collection.py:

I found a problem in your code:
When I follow your instructions above to spawn vehicles, my vehicle cannot avoid or bypass other vehicles in the environment.
How to realize that when the vehicle meets other vehicles, it can avoid and continue to move forward?
```
"""Spawn NPCs into the simulation"""

import glob
import os
import sys

try:
    sys.path.append(glob.glob('../carla/dist/carla-*%d.%d-%s.egg' % (
        sys.version_info.major,
        sys.version_info.minor,
        'win-amd64' if os.name == 'nt' else 'linux-x86_64'))[0])
except IndexError:
    pass

import carla

import argparse
import logging
import random


def main():
    argparser = argparse.ArgumentParser(
        description=__doc__)
    argparser.add_argument(
        '--host',
        metavar='H',
        default='127.0.0.1',
        help='IP of the host server (default: 127.0.0.1)')
    argparser.add_argument(
        '-p', '--port',
        metavar='P',
        default=2000,
        type=int,
        help='TCP port to listen to (default: 2000)')
    argparser.add_argument(
        '-n', '--number-of-vehicles',
        metavar='N',
        default=10,
        type=int,
        help='number of vehicles (default: 10)')
    argparser.add_argument(
        '-d', '--delay',
        metavar='D',
        default=2.0,
        type=float,
        help='delay in seconds between spawns (default: 2.0)')
    argparser.add_argument(
        '--safe',
        action='store_true',
        help='avoid spawning vehicles prone to accidents')
    args = argparser.parse_args()

    logging.basicConfig(format='%(levelname)s: %(message)s', level=logging.INFO)

    actor_list = []
    client = carla.Client(args.host, args.port)
    client.set_timeout(2.0)

    try:

        world = client.get_world()
        
        blueprints = world.get_blueprint_library().filter('vehicle.*')

        if args.safe:
            blueprints = [x for x in blueprints if int(x.get_attribute('number_of_wheels')) == 4]
            blueprints = [x for x in blueprints if not x.id.endswith('isetta')]
            blueprints = [x for x in blueprints if not x.id.endswith('carlacola')]

        spawn_points = world.get_map().get_spawn_points()
        number_of_spawn_points = len(spawn_points)

        if args.number_of_vehicles < number_of_spawn_points:
            random.shuffle(spawn_points)
        elif args.number_of_vehicles > number_of_spawn_points:
            msg = 'requested %d vehicles, but could only find %d spawn points'
            logging.warning(msg, args.number_of_vehicles, number_of_spawn_points)
            args.number_of_vehicles = number_of_spawn_points
        # --------------
        # Spawn ego vehicle
        # --------------
        ego_bp = world.get_blueprint_library().find('vehicle.tesla.model3')
        ego_bp.set_attribute('role_name','ego')
        print('\nEgo role_name is set')
        ego_color = random.choice(ego_bp.get_attribute('color').recommended_values)
        ego_bp.set_attribute('color',ego_color)
        print('\nEgo color is set')

        spawn_points = world.get_map().get_spawn_points()
        number_of_spawn_points = len(spawn_points)

        if 0 < number_of_spawn_points:
            random.shuffle(spawn_points)
            ego_transform = spawn_points[0]
            ego_vehicle = world.spawn_actor(ego_bp,ego_transform)
            print('\nEgo is spawned')
            
        else: 
            logging.warning('Could not found any spawn points')
        
        # cam_bp = None
        # cam_bp = world.get_blueprint_library().find('sensor.camera.rgb')
        # cam_bp.set_attribute("image_size_x",str(640))
        # cam_bp.set_attribute("image_size_y",str(480))
        # cam_bp.set_attribute("fov",str(105))
        # cam_location = carla.Location(2,0,1)
        # cam_rotation = carla.Rotation(180,180,180)
        # cam_transform = carla.Transform(cam_location,cam_rotation)
        # ego_cam = world.spawn_actor(cam_bp,cam_transform,attach_to=ego_vehicle)
        # if ego_vehicle.is_at_traffic_light():
        #         traffic_light = ego_vehicle.get_traffic_light()
        #         print(image.frame_number)
        #         if (ego_vehicle.get_traffic_light()).get_state() == carla.TrafficLightState.Red:
        #             #world.hud.notification("Traffic light changed! Good to go!")
        #             (ego_vehicle.get_traffic_light()).set_state(carla.TrafficLightState.Green)
        # # ego_cam.listen(lambda image: image.save_to_disk('tutorial/output/%.6d.jpg' % image.frame_number))

        # depth_cam = None
        # depth_bp = world.get_blueprint_library().find('sensor.camera.depth')
        # depth_bp.set_attribute("image_size_x",str(640))
        # depth_bp.set_attribute("image_size_y",str(480))
        # depth_bp.set_attribute("fov",str(105))
        # depth_location = carla.Location(2,0,1)
        # depth_rotation = carla.Rotation(180,180,180)
        # depth_transform = carla.Transform(depth_location,depth_rotation)
        # depth_cam = world.spawn_actor(depth_bp,depth_transform,attach_to=ego_vehicle)
        # # This time, a color converter is applied to the image, to get the semantic segmentation view
        # # depth_cam.listen(lambda image: image.save_to_disk('tutorial/new_depth_output/%.6d.jpg' % image.frame_number))
        
        spectator = world.get_spectator()
        world_snapshot = world.wait_for_tick() 
        spectator.set_transform(ego_vehicle.get_transform())
        ego_vehicle.set_autopilot(True)
        print('\nEgo autopilot enabled')



        while True:
            world_snapshot = world.wait_for_tick()
            if ego_vehicle.is_at_traffic_light():
                traffic_light = ego_vehicle.get_traffic_light()
                if (ego_vehicle.get_traffic_light()).get_state() == carla.TrafficLightState.Red:
                    (ego_vehicle.get_traffic_light()).set_state(carla.TrafficLightState.Green)

        SpawnActor = carla.command.SpawnActor
        SetAutopilot = carla.command.SetAutopilot
        FutureActor = carla.command.FutureActor

        batch = []
        for n, transform in enumerate(spawn_points):
            if n >= args.number_of_vehicles:
                break
            blueprint = random.choice(blueprints)
            if blueprint.has_attribute('color'):
                color = random.choice(blueprint.get_attribute('color').recommended_values)
                blueprint.set_attribute('color', color)
            blueprint.set_attribute('role_name', 'autopilot')
            batch.append(SpawnActor(blueprint, transform).then(SetAutopilot(FutureActor, True)))

        for response in client.apply_batch_sync(batch):
            if response.error:
                logging.error(response.error)
            else:
                actor_list.append(response.actor_id)

        print('spawned %d vehicles, press Ctrl+C to exit.' % len(actor_list))

        while True:
            world.wait_for_tick()

    finally:

        print('\ndestroying %d actors' % len(actor_list))
        client.apply_batch([carla.command.DestroyActor(x) for x in actor_list])


if __name__ == '__main__':

    try:
        main()
    except KeyboardInterrupt:
        pass
    finally:
        print('\ndone.')


```
![image](https://user-images.githubusercontent.com/36963108/102318603-8e5c2a00-3fb4-11eb-8e1c-907e9c6c28c0.png)

**Comment by MankaranSingh** [comment]
Thats strange. never happened to me. how frequently is this happening ? 

and you used this script before running other scripts right ? 
 https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/spawn_npc.py

**Comment by MankaranSingh** [comment]
or you may download the data we collected from here https://drive.google.com/file/d/1i5Y7Nd-DaWGord9ai-ngT3cn5Pa9az6p/view?usp=sharing

**Comment by KangChou** [comment]
> 真奇怪。从来没有发生在我身上。这种情况多久发生一次？
> 
> 并且您在运行其他脚本之前使用了此脚本，对吗？
> https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/spawn_npc.py

**Comment by KangChou** [comment]
> Thats strange. never happened to me. how frequently is this happening ?
> 
> and you used this script before running other scripts right ?
> https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/spawn_npc.py

Yes! I ran its spawning program first！
