### ISSUE TITLE
runing train.py:  What should I do to solve the following error? This needs your help.

### ISSUE THREAD

**Issue by KangChou** [MankaranSingh/Auto-Depth#9]
runing train.py:

What should I do to solve the following error? This needs your help.
```
Epoch 1/20
2020-12-16 15:03:45.095319: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-12-16 15:03:46.193972: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-12-16 15:03:47.085713: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "D:/Simulation_box/WindowsNoEditor/PythonAPI/Auto-Depth/train.py", line 42, in <module>
    main()
  File "D:/Simulation_box/WindowsNoEditor/PythonAPI/Auto-Depth/train.py", line 39, in main
    validation_data= val_generator)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\keras\engine\training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\keras\engine\training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\keras\engine\training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\keras\backend.py", line 3792, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\eager\function.py", line 1605, in __call__
    return self._call_impl(args, kwargs)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\eager\function.py", line 1645, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\eager\function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\eager\function.py", line 598, in call
    ctx=ctx)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node conv2d_1/convolution (defined at \Users\Anaconda3\envs\tf2-gpu\lib\site-packages\keras\backend\tensorflow_backend.py:3009) ]] [Op:__inference_keras_scratch_graph_12068]

Function call stack:
keras_scratch_graph


Process finished with exit code 1
```

**Comment by MankaranSingh** [comment]
what are the image dimensions of the dataset you are using ? 

I think this is happening because of the simple_model. 
you can replace ```model = simple_model()``` with ```model = get_denseDepth_model()``` and start training again. 

let me know if issue still persists.

**Comment by MankaranSingh** [comment]
closing due to inactivity
